services:
  db:
    image: postgres:latest
    container_name: "database"
    command: -p 5433
    environment:
      - POSTGRES_USER=${PG_TODOLIST_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
      - DATABASE_HOST=db
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "api"
    environment:
      - PG_DEFAULT_USER=postgres
      - PG_TODOLIST_USER=${PG_TODOLIST_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_HOST=db
      - PG_PORT=5433
      - API_PORT=8080
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - backend
    restart: on-failure

volumes:
  pg_volume:
networks:
  backend: